#!/bin/sh

set -e
set -x
ditdot="$(pwd)/../.."

# Needed for most themes
sudo apt-get install -y fonts-powerline

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Install plugins
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

git clone https://github.com/zsh-users/zsh-syntax-highlighting ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Copy over config
cd $ditdot/zsh
cp .* $HOME
cp agnoster.zsh-theme ~/.oh-my-zsh/themes/

# Change shell
chsh -s $(which zsh)

