# Set path variables
export PATH=$PATH:$HOME/bin:/usr/local/bin:.
export ZSH=$HOME/.oh-my-zsh

# Theme
ZSH_THEME="af-magic"

# Config variables
HYPHEN_INSENSITIVE="true"
DISABLE_UPDATE_PROMPT="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Plugins
plugins=(
    colored-man-pages
    colorize
    command-not-found
    common-aliases
    debian
    docker
    encode64
    extract
    git
    git-extras
    python
    sudo
    wd
    web-search
    yarn
    zsh-autosuggestions
    zsh-syntax-highlighting)

# Not sure what these are for
source $ZSH/oh-my-zsh.sh
zstyle :completion::complete:-command-:: tag-order local-directories .
setopt autocd
setopt +o nomatch
